#=============== BUILD ================
FROM node:16

WORKDIR /usr/app/weweb-preview
COPY . .

RUN npm install --quiet
RUN npm run build

#=========== ENV VARIABLES ============
ENV NODE_ENV=production

#CACHE_PATH
ARG CACHE_PATH
ENV CACHE_PATH=$CACHE_PATH
#PUBLIC_KEY
ARG PUBLIC_KEY
ENV PUBLIC_KEY=$PUBLIC_KEY
#PRIVATE_KEY
ARG PRIVATE_KEY
ENV PRIVATE_KEY=$PRIVATE_KEY

#======= OPTIONAL ENV VARIABLES =======
#PORT
ARG PORT=3160
ENV PORT=$PORT
#SERVER_PATH
ARG SERVER_PATH
ENV SERVER_PATH=$SERVER_PATH
#WW_LOG_LEVEL
ARG WW_LOG_LEVEL=trace
ENV WW_LOG_LEVEL=$WW_LOG_LEVEL

#--RDS CONNECTION--
#RDS_DB_NAME
ARG RDS_DB_NAME
ENV RDS_DB_NAME=$RDS_DB_NAME
#RDS_USERNAME
ARG RDS_USERNAME
ENV RDS_USERNAME=$RDS_USERNAME
#RDS_PASSWORD
ARG RDS_PASSWORD
ENV RDS_PASSWORD=$RDS_PASSWORD
#RDS_HOSTNAME
ARG RDS_HOSTNAME
ENV RDS_HOSTNAME=$RDS_HOSTNAME
#RDS_PORT
ARG RDS_PORT
ENV RDS_PORT=$RDS_PORT

#--DB CONNECTION--
#Required if RDS CONNECTION not set
#DB_NAME
ARG DB_NAME
ENV DB_NAME=$DB_NAME
#DB_USERNAME
ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME
#DB_PASSWORD
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
#DB_HOSTNAME
ARG DB_HOSTNAME
ENV DB_HOSTNAME=$DB_HOSTNAME
#DB_PORT
ARG DB_PORT
ENV DB_PORT=$DB_PORT

#--S3 & COGNITO CONFIGURATION--
#AWS_ACCESS_KEY_ID
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#AWS_SECRET_ACCESS_KEY
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#BUCKETREGION
ARG BUCKETREGION
ENV BUCKETREGION=$BUCKETREGION
#BUCKETNAME
ARG BUCKETNAME
ENV BUCKETNAME=$BUCKETNAME


#============ EXPOSE PORTS ============
EXPOSE $PORT
EXPOSE 3161
EXPOSE 3162
EXPOSE 3163


#============= START CMD ==============
CMD npm run start